{{- if and .Values.data.persistentVolumeClaim.enabled .Values.data.prepare.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "omop-lite.fullname" . }}-prepare-data
  labels:
    {{- include "omop-lite.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        {{- include "omop-lite.labels" . | nindent 8 }}
    spec:
      containers:
      - name: prepare
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - |
          mkdir -p {{ .Values.env.dataDir }}
          cp -r /source/* {{ .Values.env.dataDir }}/
        volumeMounts:
        - name: data
          mountPath: {{ .Values.env.dataDir }}
        - name: source
          mountPath: /source
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ if .Values.data.persistentVolumeClaim.existingClaim }}{{ .Values.data.persistentVolumeClaim.existingClaim }}{{ else }}{{ include "omop-lite.fullname" . }}-data{{ end }}
      - name: source
        hostPath:
          path: {{ .Values.data.prepare.sourcePath }}
          type: Directory
      restartPolicy: Never
{{- end }} 