version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "fix(dependencies): "
    groups:
      python-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      python-major:
        patterns:
          - "*"
        update-types:
          - "major"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "chore(dependencies): "
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
          - "major"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "chore(dependencies): "
    groups:
      docker:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
          - "major"
  - package-ecosystem: "docker"
    directory: "/text-search"
    schedule:
      interval: "monthly"
      day: "monday"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "chore(dependencies): "
    groups:
      docker:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
          - "major"
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "chore(dependencies): "
    groups:
      docker-compose:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
          - "major"
