name: omop-ts

services:
   omop-ts:
    image: pgvector/pgvector:pg17
    environment:
      - POSTGRES_DB=omop
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
   
   omop-lite:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=omop-ts
      - DB_PASSWORD=password
      - SCHEMA_NAME=cdm
      - FTS_CREATE=1
    volumes:
      - ./data:/data
    depends_on:
      omop-ts:
        condition: service_healthy
   
   embeddings:
     build:
       context: ./embeddings
       dockerfile: Dockerfile
     environment:
      - DB_HOST=omop-ts
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=omop
      - SCHEMA_NAME=cdm
     volumes:
       - ./embeddings:/embeddings:ro
     depends_on:
       omop-lite:
         condition: service_completed_successfully

