name: omop-ts

services:
   omop-ts:
    image: pgvector/pgvector:pg17
    environment:
      - POSTGRES_DB=omop
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
   
   omop-lite:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SCHEMA_NAME=cdm
    volumes:
      - ./vocabs:/vocabs
    depends_on:
      - omop-ts
   
   embeddings:
     build:
       context: ./embeddings
       dockerfile: Dockerfile
     environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=omop
      - SCHEMA_NAME=cdm
     volumes:
       - ./embeddings:/embeddings
     depends_on:
       omop-lite:
         - service_completed_successfully

