env:
  dbHost: postgres
  dbPort: "5432"
  dbUser: postgres
  dbPassword: postgres
  dbName: omop
  dialect: postgresql
  schemaName: public
  synthetic: true
  synthetic_number: 1000
  log_level: DEBUG
