"""Add constraints

Revision ID: 3da18f79ff7b
Revises: bbf6835f69e1
Create Date: 2025-03-22 18:31:54.602686

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic import context


# revision identifiers, used by Alembic.
revision: str = "3da18f79ff7b"
down_revision: Union[str, None] = "bbf6835f69e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Get schema from config
    schema = context.config.attributes["schema"]

    # Create indexes with schema-qualified table names
    op.create_index(
        "idx_care_site_id_1", "care_site", ["care_site_id"], unique=False, schema=schema
    )
    op.create_index(
        "idx_concept_class_id",
        "concept",
        ["concept_class_id"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        "idx_concept_code", "concept", ["concept_code"], unique=False, schema=schema
    )
    op.create_index(
        "idx_concept_concept_id", "concept", ["concept_id"], unique=False, schema=schema
    )
    op.create_index(
        "idx_concept_domain_id", "concept", ["domain_id"], unique=False, schema=schema
    )
    op.create_index(
        "idx_concept_vocabulary_id",
        "concept",
        ["vocabulary_id"],
        unique=False,
        schema=schema,
    )

    # Create foreign keys with schema-qualified table names and explicit constraint names
    op.create_foreign_key(
        "fk_care_site_concept",
        "care_site",
        "concept",
        ["place_of_service_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_care_site_location",
        "care_site",
        "location",
        ["location_id"],
        ["location_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_cohort_definition_concept_1",
        "cohort_definition",
        "concept",
        ["definition_type_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_cohort_definition_concept_2",
        "cohort_definition",
        "concept",
        ["subject_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_concept_ancestor_ancestor_concept_id",
        "concept_ancestor",
        "concept",
        ["ancestor_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_concept_ancestor_descendant_concept_id",
        "concept_ancestor",
        "concept",
        ["descendant_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_concept_class_concept_id",
        "concept_class",
        "concept",
        ["concept_class_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_concept_relationship_concept_id_2",
        "concept_relationship",
        "concept",
        ["concept_id_2"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_concept_relationship_concept_id_1",
        "concept_relationship",
        "concept",
        ["concept_id_1"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_concept_relationship_relationship_id",
        "concept_relationship",
        "relationship",
        ["relationship_id"],
        ["relationship_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_concept_synonym_concept_id",
        "concept_synonym",
        "concept",
        ["concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_concept_synonym_language_concept_id",
        "concept_synonym",
        "concept",
        ["language_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_condition_era_concept_id",
        "condition_era",
        "concept",
        ["condition_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_condition_era_person_id",
        "condition_era",
        "person",
        ["person_id"],
        ["person_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_index(
        "idx_condition_concept_id_1",
        "condition_occurrence",
        ["condition_concept_id"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        "idx_condition_person_id_1",
        "condition_occurrence",
        ["person_id"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        "idx_condition_visit_id_1",
        "condition_occurrence",
        ["visit_occurrence_id"],
        unique=False,
        schema=schema,
    )
    op.create_foreign_key(
        "fk_condition_occurrence_provider_id",
        "condition_occurrence",
        "provider",
        ["provider_id"],
        ["provider_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_condition_occurrence_visit_occurrence_id",
        "condition_occurrence",
        "visit_occurrence",
        ["visit_occurrence_id"],
        ["visit_occurrence_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_condition_occurrence_person_id",
        "condition_occurrence",
        "person",
        ["person_id"],
        ["person_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_condition_occurrence_condition_type_concept_id",
        "condition_occurrence",
        "concept",
        ["condition_type_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_condition_occurrence_visit_detail_id",
        "condition_occurrence",
        "visit_detail",
        ["visit_detail_id"],
        ["visit_detail_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_condition_occurrence_condition_concept_id",
        "condition_occurrence",
        "concept",
        ["condition_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_condition_occurrence_condition_source_concept_id",
        "condition_occurrence",
        "concept",
        ["condition_source_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_condition_occurrence_condition_status_concept_id",
        "condition_occurrence",
        "concept",
        ["condition_status_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_cost_concept_id",
        "cost",
        "concept",
        ["cost_type_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_cost_drg_concept_id",
        "cost",
        "concept",
        ["drg_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_cost_domain_id",
        "cost",
        "domain",
        ["cost_domain_id"],
        ["domain_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_cost_revenue_code_concept_id",
        "cost",
        "concept",
        ["revenue_code_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_cost_currency_concept_id",
        "cost",
        "concept",
        ["currency_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_death_cause_concept_id",
        "death",
        "concept",
        ["cause_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_death_death_type_concept_id",
        "death",
        "concept",
        ["death_type_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_death_cause_source_concept_id",
        "death",
        "concept",
        ["cause_source_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_death_person_id",
        "death",
        "person",
        ["person_id"],
        ["person_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_device_exposure_concept_id",
        "device_exposure",
        "concept",
        ["device_source_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_device_exposure_provider_id",
        "device_exposure",
        "provider",
        ["provider_id"],
        ["provider_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_device_exposure_device_type_concept_id",
        "device_exposure",
        "concept",
        ["device_type_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_device_exposure_visit_occurrence_id",
        "device_exposure",
        "visit_occurrence",
        ["visit_occurrence_id"],
        ["visit_occurrence_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_device_exposure_unit_source_concept_id",
        "device_exposure",
        "concept",
        ["unit_source_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_device_exposure_device_concept_id",
        "device_exposure",
        "concept",
        ["device_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_device_exposure_person_id",
        "device_exposure",
        "person",
        ["person_id"],
        ["person_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_device_exposure_unit_concept_id",
        "device_exposure",
        "concept",
        ["unit_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_device_exposure_visit_detail_id",
        "device_exposure",
        "visit_detail",
        ["visit_detail_id"],
        ["visit_detail_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_domain_concept_id",
        "domain",
        "concept",
        ["domain_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_dose_era_person_id",
        "dose_era",
        "person",
        ["person_id"],
        ["person_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_dose_era_concept_id",
        "dose_era",
        "concept",
        ["drug_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_dose_era_unit_concept_id",
        "dose_era",
        "concept",
        ["unit_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_drug_era_concept_id",
        "drug_era",
        "concept",
        ["drug_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_drug_era_person_id",
        "drug_era",
        "person",
        ["person_id"],
        ["person_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_drug_exposure_concept_id",
        "drug_exposure",
        "concept",
        ["drug_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_drug_exposure_visit_occurrence_id",
        "drug_exposure",
        "visit_occurrence",
        ["visit_occurrence_id"],
        ["visit_occurrence_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_drug_exposure_drug_source_concept_id",
        "drug_exposure",
        "concept",
        ["drug_source_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_drug_exposure_provider_id",
        "drug_exposure",
        "provider",
        ["provider_id"],
        ["provider_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_drug_exposure_person_id",
        "drug_exposure",
        "person",
        ["person_id"],
        ["person_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_drug_exposure_visit_detail_id",
        "drug_exposure",
        "visit_detail",
        ["visit_detail_id"],
        ["visit_detail_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_drug_exposure_drug_type_concept_id",
        "drug_exposure",
        "concept",
        ["drug_type_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_drug_exposure_route_concept_id",
        "drug_exposure",
        "concept",
        ["route_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_drug_strength_denominator_unit_concept_id",
        "drug_strength",
        "concept",
        ["denominator_unit_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_drug_strength_numerator_unit_concept_id",
        "drug_strength",
        "concept",
        ["numerator_unit_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_drug_strength_amount_unit_concept_id",
        "drug_strength",
        "concept",
        ["amount_unit_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_drug_strength_drug_concept_id",
        "drug_strength",
        "concept",
        ["drug_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_drug_strength_ingredient_concept_id",
        "drug_strength",
        "concept",
        ["ingredient_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_episode_concept_id",
        "episode",
        "concept",
        ["episode_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_episode_source_concept_id",
        "episode",
        "concept",
        ["episode_source_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_episode_object_concept_id",
        "episode",
        "concept",
        ["episode_object_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_episode_type_concept_id",
        "episode",
        "concept",
        ["episode_type_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_episode_person_id",
        "episode",
        "person",
        ["person_id"],
        ["person_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_episode_event_episode_event_field_concept_id",
        "episode_event",
        "concept",
        ["episode_event_field_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_episode_event_episode_id",
        "episode_event",
        "episode",
        ["episode_id"],
        ["episode_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_index(
        "idx_fact_relationship_id1",
        "fact_relationship",
        ["domain_concept_id_1"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        "idx_fact_relationship_id2",
        "fact_relationship",
        ["domain_concept_id_2"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        "idx_fact_relationship_id3",
        "fact_relationship",
        ["relationship_concept_id"],
        unique=False,
        schema=schema,
    )
    op.create_foreign_key(
        "fk_fact_relationship_relationship_concept_id",
        "fact_relationship",
        "concept",
        ["relationship_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_fact_relationship_domain_concept_id_1",
        "fact_relationship",
        "concept",
        ["domain_concept_id_1"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_fact_relationship_domain_concept_id_2",
        "fact_relationship",
        "concept",
        ["domain_concept_id_2"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_index(
        "idx_location_id_1",
        "location",
        ["location_id"],
        unique=False,
        schema=schema,
    )
    op.create_foreign_key(
        "fk_location_country_concept_id",
        "location",
        "concept",
        ["country_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_measurement_visit_occurrence_id",
        "measurement",
        "visit_occurrence",
        ["visit_occurrence_id"],
        ["visit_occurrence_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_measurement_operator_concept_id",
        "measurement",
        "concept",
        ["operator_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_measurement_value_as_concept_id",
        "measurement",
        "concept",
        ["value_as_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_measurement_person_id",
        "measurement",
        "person",
        ["person_id"],
        ["person_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_measurement_unit_concept_id",
        "measurement",
        "concept",
        ["unit_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_measurement_visit_detail_id",
        "measurement",
        "visit_detail",
        ["visit_detail_id"],
        ["visit_detail_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_measurement_measurement_source_concept_id",
        "measurement",
        "concept",
        ["measurement_source_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_measurement_unit_source_concept_id",
        "measurement",
        "concept",
        ["unit_source_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_measurement_measurement_concept_id",
        "measurement",
        "concept",
        ["measurement_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_measurement_meas_event_field_concept_id",
        "measurement",
        "concept",
        ["meas_event_field_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_measurement_provider_id",
        "measurement",
        "provider",
        ["provider_id"],
        ["provider_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_measurement_measurement_type_concept_id",
        "measurement",
        "concept",
        ["measurement_type_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_metadata_concept_id",
        "metadata",
        "concept",
        ["metadata_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_metadata_metadata_type_concept_id",
        "metadata",
        "concept",
        ["metadata_type_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_metadata_value_as_concept_id",
        "metadata",
        "concept",
        ["value_as_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_note_visit_detail_id",
        "note",
        "visit_detail",
        ["visit_detail_id"],
        ["visit_detail_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_note_provider_id",
        "note",
        "provider",
        ["provider_id"],
        ["provider_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_note_note_event_field_concept_id",
        "note",
        "concept",
        ["note_event_field_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_note_language_concept_id",
        "note",
        "concept",
        ["language_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_note_encoding_concept_id",
        "note",
        "concept",
        ["encoding_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_note_person_id",
        "note",
        "person",
        ["person_id"],
        ["person_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_note_visit_occurrence_id",
        "note",
        "visit_occurrence",
        ["visit_occurrence_id"],
        ["visit_occurrence_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_note_note_type_concept_id",
        "note",
        "concept",
        ["note_type_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_note_note_class_concept_id",
        "note",
        "concept",
        ["note_class_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_index(
        "idx_note_nlp_concept_id_1",
        "note_nlp",
        ["note_nlp_concept_id"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        "idx_note_nlp_note_id_1",
        "note_nlp",
        ["note_id"],
        unique=False,
        schema=schema,
    )
    op.create_foreign_key(
        "fk_note_nlp_note_nlp_concept_id",
        "note_nlp",
        "concept",
        ["note_nlp_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_note_nlp_note_nlp_source_concept_id",
        "note_nlp",
        "concept",
        ["note_nlp_source_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_note_nlp_section_concept_id",
        "note_nlp",
        "concept",
        ["section_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_observation_person_id",
        "observation",
        "person",
        ["person_id"],
        ["person_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_observation_visit_occurrence_id",
        "observation",
        "visit_occurrence",
        ["visit_occurrence_id"],
        ["visit_occurrence_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_observation_obs_event_field_concept_id",
        "observation",
        "concept",
        ["obs_event_field_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_observation_value_as_concept_id",
        "observation",
        "concept",
        ["value_as_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_observation_provider_id",
        "observation",
        "provider",
        ["provider_id"],
        ["provider_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_observation_observation_source_concept_id",
        "observation",
        "concept",
        ["observation_source_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_observation_unit_concept_id",
        "observation",
        "concept",
        ["unit_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_observation_visit_detail_id",
        "observation",
        "visit_detail",
        ["visit_detail_id"],
        ["visit_detail_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_observation_observation_type_concept_id",
        "observation",
        "concept",
        ["observation_type_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_observation_observation_concept_id",
        "observation",
        "concept",
        ["observation_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_observation_qualifier_concept_id",
        "observation",
        "concept",
        ["qualifier_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_index(
        "idx_observation_period_id_1",
        "observation_period",
        ["person_id"],
        unique=False,
        schema=schema,
    )
    op.create_foreign_key(
        "fk_observation_period_person_id",
        "observation_period",
        "person",
        ["person_id"],
        ["person_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_observation_period_period_type_concept_id",
        "observation_period",
        "concept",
        ["period_type_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_payer_plan_period_stop_reason_concept_id",
        "payer_plan_period",
        "concept",
        ["stop_reason_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_payer_plan_period_payer_concept_id",
        "payer_plan_period",
        "concept",
        ["payer_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_payer_plan_period_plan_concept_id",
        "payer_plan_period",
        "concept",
        ["plan_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_payer_plan_period_payer_source_concept_id",
        "payer_plan_period",
        "concept",
        ["payer_source_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_payer_plan_period_person_id",
        "payer_plan_period",
        "person",
        ["person_id"],
        ["person_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_payer_plan_period_plan_source_concept_id",
        "payer_plan_period",
        "concept",
        ["plan_source_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_payer_plan_period_stop_reason_source_concept_id",
        "payer_plan_period",
        "concept",
        ["stop_reason_source_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_payer_plan_period_sponsor_concept_id",
        "payer_plan_period",
        "concept",
        ["sponsor_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_payer_plan_period_sponsor_source_concept_id",
        "payer_plan_period",
        "concept",
        ["sponsor_source_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_index(
        "idx_gender",
        "person",
        ["gender_concept_id"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        "idx_person_id_1",
        "person",
        ["person_id"],
        unique=False,
        schema=schema,
    )
    op.create_foreign_key(
        "fk_person_ethnicity_concept_id",
        "person",
        "concept",
        ["ethnicity_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_person_race_concept_id",
        "person",
        "concept",
        ["race_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_person_gender_concept_id",
        "person",
        "concept",
        ["gender_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_person_provider_id",
        "person",
        "provider",
        ["provider_id"],
        ["provider_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_person_gender_source_concept_id",
        "person",
        "concept",
        ["gender_source_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_person_care_site_id",
        "person",
        "care_site",
        ["care_site_id"],
        ["care_site_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_person_race_source_concept_id",
        "person",
        "concept",
        ["race_source_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_person_location_id",
        "person",
        "location",
        ["location_id"],
        ["location_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_person_ethnicity_source_concept_id",
        "person",
        "concept",
        ["ethnicity_source_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_procedure_occurrence_concept_id",
        "procedure_occurrence",
        "concept",
        ["procedure_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_procedure_occurrence_type_concept_id",
        "procedure_occurrence",
        "concept",
        ["procedure_type_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_procedure_occurrence_visit_detail_id",
        "procedure_occurrence",
        "visit_detail",
        ["visit_detail_id"],
        ["visit_detail_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_procedure_occurrence_provider_id",
        "procedure_occurrence",
        "provider",
        ["provider_id"],
        ["provider_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_procedure_occurrence_modifier_concept_id",
        "procedure_occurrence",
        "concept",
        ["modifier_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_procedure_occurrence_person_id",
        "procedure_occurrence",
        "person",
        ["person_id"],
        ["person_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_procedure_occurrence_visit_occurrence_id",
        "procedure_occurrence",
        "visit_occurrence",
        ["visit_occurrence_id"],
        ["visit_occurrence_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_procedure_occurrence_procedure_source_concept_id",
        "procedure_occurrence",
        "concept",
        ["procedure_source_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_index(
        "idx_provider_id_1",
        "provider",
        ["provider_id"],
        unique=False,
        schema=schema,
    )
    op.create_foreign_key(
        "fk_provider_care_site_id",
        "provider",
        "care_site",
        ["care_site_id"],
        ["care_site_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_provider_gender_concept_id",
        "provider",
        "concept",
        ["gender_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_provider_gender_source_concept_id",
        "provider",
        "concept",
        ["gender_source_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_provider_specialty_concept_id",
        "provider",
        "concept",
        ["specialty_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_relationship_relationship_concept_id",
        "relationship",
        "concept",
        ["relationship_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_source_to_concept_map_target_concept_id",
        "source_to_concept_map",
        "concept",
        ["target_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_source_to_concept_map_target_vocabulary_id",
        "source_to_concept_map",
        "vocabulary",
        ["target_vocabulary_id"],
        ["vocabulary_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_source_to_concept_map_source_concept_id",
        "source_to_concept_map",
        "concept",
        ["source_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_specimen_person_id",
        "specimen",
        "person",
        ["person_id"],
        ["person_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_specimen_unit_concept_id",
        "specimen",
        "concept",
        ["unit_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_specimen_specimen_type_concept_id",
        "specimen",
        "concept",
        ["specimen_type_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_specimen_anatomic_site_concept_id",
        "specimen",
        "concept",
        ["anatomic_site_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_specimen_disease_status_concept_id",
        "specimen",
        "concept",
        ["disease_status_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_specimen_specimen_concept_id",
        "specimen",
        "concept",
        ["specimen_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_index(
        "idx_visit_det_concept_id_1",
        "visit_detail",
        ["visit_detail_concept_id"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        "idx_visit_det_occ_id",
        "visit_detail",
        ["visit_occurrence_id"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        "idx_visit_det_person_id_1",
        "visit_detail",
        ["person_id"],
        unique=False,
        schema=schema,
    )
    op.create_foreign_key(
        "fk_visit_detail_preceding_visit_detail_id",
        "visit_detail",
        "visit_detail",
        ["preceding_visit_detail_id"],
        ["visit_detail_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_visit_detail_admitted_from_concept_id",
        "visit_detail",
        "concept",
        ["admitted_from_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_visit_detail_discharged_to_concept_id",
        "visit_detail",
        "concept",
        ["discharged_to_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_visit_detail_visit_occurrence_id",
        "visit_detail",
        "visit_occurrence",
        ["visit_occurrence_id"],
        ["visit_occurrence_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_visit_detail_visit_detail_source_concept_id",
        "visit_detail",
        "concept",
        ["visit_detail_source_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_visit_detail_care_site_id",
        "visit_detail",
        "care_site",
        ["care_site_id"],
        ["care_site_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_visit_detail_parent_visit_detail_id",
        "visit_detail",
        "visit_detail",
        ["parent_visit_detail_id"],
        ["visit_detail_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_visit_detail_person_id",
        "visit_detail",
        "person",
        ["person_id"],
        ["person_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_visit_detail_visit_detail_type_concept_id",
        "visit_detail",
        "concept",
        ["visit_detail_type_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_visit_detail_visit_detail_concept_id",
        "visit_detail",
        "concept",
        ["visit_detail_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_visit_detail_provider_id",
        "visit_detail",
        "provider",
        ["provider_id"],
        ["provider_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_index(
        "idx_visit_concept_id_1",
        "visit_occurrence",
        ["visit_concept_id"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        "idx_visit_person_id_1",
        "visit_occurrence",
        ["person_id"],
        unique=False,
        schema=schema,
    )
    op.create_foreign_key(
        "fk_visit_occurrence_preceding_visit_occurrence_id",
        "visit_occurrence",
        "visit_occurrence",
        ["preceding_visit_occurrence_id"],
        ["visit_occurrence_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_visit_occurrence_discharged_to_concept_id",
        "visit_occurrence",
        "concept",
        ["discharged_to_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_visit_occurrence_person_id",
        "visit_occurrence",
        "person",
        ["person_id"],
        ["person_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_visit_occurrence_provider_id",
        "visit_occurrence",
        "provider",
        ["provider_id"],
        ["provider_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_visit_occurrence_visit_source_concept_id",
        "visit_occurrence",
        "concept",
        ["visit_source_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_visit_occurrence_care_site_id",
        "visit_occurrence",
        "care_site",
        ["care_site_id"],
        ["care_site_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_visit_occurrence_visit_type_concept_id",
        "visit_occurrence",
        "concept",
        ["visit_type_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_visit_occurrence_admitted_from_concept_id",
        "visit_occurrence",
        "concept",
        ["admitted_from_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_visit_occurrence_visit_concept_id",
        "visit_occurrence",
        "concept",
        ["visit_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    op.create_foreign_key(
        "fk_vocabulary_concept_id",
        "vocabulary",
        "concept",
        ["vocabulary_concept_id"],
        ["concept_id"],
        source_schema=schema,
        referent_schema=schema,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    pass
