image:
  repository: ghcr.io/health-informatics-uon/omop-lite
  tag: v0.0.11
  pullPolicy: IfNotPresent

env:
  dbHost: postgres
  dbPort: "5432"
  dbUser: postgres
  dbPassword: postgres
  dbName: omop
  dialect: postgresql
  schemaName: public
  dataDir: /data
  synthetic: true

backoffLimit: 1
