image:
  repository: ghcr.io/health-informatics-uon/omop-lite
  tag: v0.0.11
  pullPolicy: IfNotPresent

env:
  dbHost: postgres
  dbPort: "5432"
  dbUser: postgres
  dbPassword: postgres
  dbName: omop_helm
  dialect: postgresql
  schemaName: public
  synthetic: "true"

persistence:
  enabled: false

backoffLimit: 1

serviceAccount:
  create: false
  automount: false

# Placeholder values to prevent template errors
ingress:
  enabled: false

service:
  type: ClusterIP
  port: 8080 