image:
  repository: ghcr.io/health-informatics-uon/omop-lite
  tag: 0.0.11
  pullPolicy: IfNotPresent

env:
  dbHost: your-postgres-service
  dbPort: 5432
  dbUser: postgres
  dbPassword: password
  dbName: omop
  dialect: postgresql
  schemaName: public
  dataDir: /data
  synthetic: true

persistence:
  enabled: false
  size: 10Gi
  storageClass: standard 