image:
  repository: ghcr.io/health-informatics-uon/omop-lite
  tag: 0.0.11
  pullPolicy: IfNotPresent

env:
  dbHost: your-postgres-service
  dbPort: "5432"
  dbUser: postgres
  dbPassword: password
  dbName: omop
  dialect: postgresql
  schemaName: public
  dataDir: /data
  synthetic: true

backoffLimit: 1

serviceAccount:
  create: false
  automount: false

# Placeholder values to prevent template errors
ingress:
  enabled: false

service:
  type: ClusterIP
  port: 8080

persistence:
  enabled: false
  size: 10Gi
  storageClass: standard 